### ISSUE TITLE
IK mit führender Null führt zu Validierungsfehlern

### ISSUE THREAD

**Issue by oboehm** [oboehm/jfachwert#20]
Es gibt IKs wie 021462398, die eine führende Null besitzen. Diese führen aber aktuell in 5.1.0 zu einem Validierungsfehler:

```
'21462398': length (8) is not between 9 and 9
de.jfachwert.pruefung.exception.LocalizedIllegalArgumentException: Feld=[21462398]: Länge ist 1 statt 9
	at de.jfachwert.KSimpleValidator$DefaultImpls.verify(KSimpleValidator.kt:75)
	at de.jfachwert.med.IK$Validator.verify(IK.kt:103)
	at de.jfachwert.med.IK$Validator.verify(IK.kt:103)
	at de.jfachwert.AbstractFachwert.<init>(AbstractFachwert.kt:48)
	at de.jfachwert.med.IK.<init>(IK.kt:52)
	at de.jfachwert.med.IK.<init>(IK.kt:52)
	at de.jfachwert.med.IK$Companion$of$1.invoke(IK.kt:154)
	at de.jfachwert.med.IK$Companion$of$1.invoke(IK.kt:154)
	at de.jfachwert.med.IK$Companion.of$lambda$0(IK.kt:154)
	at java.base/java.util.Map.computeIfAbsent(Map.java:1054)
	at de.jfachwert.med.IK$Companion.of(IK.kt:154)
	at de.jfachwert.med.IK$Companion.of(IK.kt:165)
	at de.jfachwert.med.IK.of(IK.kt)
```

**Comment by oboehm** [comment]
Fixed mit 5.1.1
