### ISSUE TITLE
Initialisierung FachwertFactory schlägt fehl, wenn javax.money:money-api fehlt

### ISSUE THREAD

**Issue by oboehm** [oboehm/jfachwert#25]
Wenn die Bibliothek javax.money:money-api nicht als Dependency definiert ist, scheitert die Initialisierung der FachwertFactory:

```
java.lang.NoClassDefFoundError: javax/money/MonetaryAmount

	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at de.jfachwert.FachwertFactory.<clinit>(FachwertFactory.kt:192)
```

Die Ursache ist die Registrierung der Geldbetrag-Klasse. In diesem Fall soll diese Klasse für die Registrierung ignoriert werden.

**Comment by oboehm** [comment]
Mit 5.4.3 behoben
