### ISSUE TITLE
Fehler in TinyUUID.fromString: Illegal base64 character 2d

### ISSUE THREAD

**Issue by oboehm** [oboehm/jfachwert#5]
In seltenen Fällen kann es beim Aufruf der fromString-Methode von TinyUUID zu folgender Exception kommen:

> java.lang.IllegalArgumentException: Illegal base64 character 2d
	at java.util.Base64$Decoder.decode0(Base64.java:714)
	at java.util.Base64$Decoder.decode(Base64.java:526)
	at de.jfachwert.util.TinyUUID.fromString(TinyUUID.java:237)

s.a. [Build #348](https://travis-ci.org/oboehm/jfachwert/builds/384174174)

**Comment by oboehm** [comment]
Closed with v0.7.1
